### ISSUE TITLE
Usage in Windows 10

### ISSUE THREAD

**Issue by checor** [e-fever/qtcwizard#1]
Hello, thanks for this awesome project!

I'm trying to use this project in Windows 10. After installing I do `qtcwizard init` and then `qtcwizard install`.  Then this error appears:
```
target = shell.env("APPDATA") + "/QtProject/qtcreator/templates/wizards"

TypeError: shell.env is not a function
    at Command.<anonymous> (C:\cygwin64\home\Temp\qtcwizard\qtcwizard.js:42:28)
    at Command.listener (C:\cygwin64\home\Temp\qtcwizard\node_modules\commander\index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (C:\cygwin64\home\Temp\qtcwizard\node_modules\commander\index.js:651:12)
    at Command.parse (C:\cygwin64\home\Temp\qtcwizard\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (C:\cygwin64\home\Temp\qtcwizard\qtcwizard.js:85:9)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
```

It seems that fails after a normal resquest of the %APPDATA% path location. I'm not familiarized with node.js, but I will try to find the error and report results.

Cheers!

**Comment by benlau** [comment]
hi @checor,

Thanks for reporting the problem. I have checked the source. It is a typo in the source code . I have just fixed with latest commit. Could you check about it?

**Comment by checor** [comment]
Yes, that corrected that error. However, I remember that I needed to create a folder inside %APPDATA% to get the command working (I've never made a custom template in Qt Creator).

Also, the install command said it was sucess, but I don't see the new template. I will run it in verbose mode for templates and report back later.

**Comment by benlau** [comment]
hi @checor ,

I just fixed it. Please check about the latest version.
